# test profile
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:agileHub;Mode=MySQL;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 100

    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: debug
    root: info
    org.hibernate.orm.jdbc.bind: trace