# test profile
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 100


  sql:
    init:
      mode: never

server:
  url: http://localhost:8080
  port: 8080