name: book-challenge 
on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 21를 설치합니다
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: 그래들 캐시
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: 그래들 설치 
        uses: gradle/actions/setup-gradle@v4
      
      - name: Gradle 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew
        
      - name: Gradle build를 수행합니다
        run: ./gradlew build
